In [49]:
import pandas as pd

In [50]:
with open("tab_detalhe_modal (7)_Dados completos_data (2).csv", "r", encoding="latin-1") as f:
    print(f.readline())

"CD_Resp	cidade_cliente	transportador	PEDIDO 1P/FULL"

In [60]:
df_tab = pd.read_csv(
    "tab_detalhe_modal (7)_Dados completos_data (2).csv",
    sep="\t",
    quoting=3,        # Desabilita tratamento de aspas
    engine="python",
    encoding="latin-1"
)

In [61]:
df_tab.head(5)

  "CD_Resp cidade_cliente transportador PEDIDO 1P/FULL"
0    "1100        GOIANIA     PORTA APO     1115971792"
1    "1100        GOIANIA     PORTA APO     1116115099"
2    "1100        GOIANIA     PORTA APO     1116051634"
3    "1100        GOIANIA     PORTA APO     1116111441"
4    "1100        GOIANIA     PORTA APO     1116116815"

In [63]:
df_tab.to_csv("saida_tab.csv", sep="\t", index=False, encoding="latin-1")

In [62]:
df_tab.columns

Index(['"CD_Resp', 'cidade_cliente', 'transportador', 'PEDIDO 1P/FULL"'], dtype='object')

In [47]:
df_tab = df_tab.applymap(lambda x: x.strip('"') if isinstance(x, str) else x)

C:\Users\tauam.pinheiro\AppData\Local\Temp\ipykernel_10860\2208148980.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_tab = df_tab.applymap(lambda x: x.strip('"') if isinstance(x, str) else x)

In [48]:
df_tab.columns

Index(['"CD_Resp', 'cidade_cliente', 'transportador', 'PEDIDO 1P/FULL"'], dtype='object')

KeyError: "None of [Index(['PEDIDO 1P/FULL '], dtype='object')] are in the [columns]"

In [26]:
import os

In [5]:
preventiva = pd.read_csv("cd-etapa (3)_Dados completos_data - 2025-10-17T075817.370 (2).csv", sep='\t', encoding='latin-1')

In [6]:
relatorio_preventiva = pd.read_excel('Relatorio_DOMICILIO_2025-10-31 (2).xlsx')

In [13]:
mobile_relatorio = pd.read_excel('20251018091706-43794990000190-entregas.xls')

In [8]:
mobile_relatorio.head(5)

,Pedido Cliente,Pedido,UUID,Romaneio,Transportador,Nota Fiscal,Numero de Série,Data Importação Pedido,Data de Captura,Data de Processamento,Entregador,Tipo
0,1474270272545078,1.099514e+09,d88b235e-7bac-4d29-a580-dc1000708486,114001715.0,PORTA A PORTA TRANSPORTES LTDA,102962,7,01/10/25 06:45,01/10/25 15:12,01/10/25 15:12,MARCELO SILVA DE CARVALHO(GOIANIA),Entrega Realizada Normalmente
1,1474450186521141,1.099603e+09,a3b6ef87-50ad-48a2-8640-4593405fe389,114001715.0,PORTA A PORTA TRANSPORTES LTDA,103335,7,01/10/25 06:45,01/10/25 15:13,01/10/25 15:13,MARCELO SILVA DE CARVALHO(GOIANIA),Entrega Realizada Normalmente
2,1099617993,1.099618e+09,c6344b33-682c-4d5e-8f94-8cbd3724c55a,114001715.0,PORTA A PORTA TRANSPORTES LTDA,103333,7,01/10/25 06:45,01/10/25 17:03,01/10/25 17:03,MARCELO SILVA DE CARVALHO(GOIANIA),Entrega Realizada Normalmente
3,1099626099,1.099626e+09,b3932f98-46a5-4ee4-bf34-d6a84f682118,114001715.0,PORTA A PORTA TRANSPORTES LTDA,103334,7,01/10/25 06:45,01/10/25 15:13,01/10/25 15:13,MARCELO SILVA DE CARVALHO(GOIANIA),Entrega Realizada Normalmente
4,1474370272598717,1.099629e+09,54d54f52-e4de-4140-aa4e-731b8da5c16d,114001715.0,PORTA A PORTA TRANSPORTES LTDA,103336,7,01/10/25 06:45,01/10/25 15:10,01/10/25 15:10,MARCELO SILVA DE CARVALHO(GOIANIA),Entrega Realizada Normalmente

In [14]:
mobile_relatorio.Tipo.unique()

array(['Entrega Realizada Normalmente', 'Mercadoria devolvida ao CD',
       'Entregue na loja', 'Entregue na Base do transportador',
       'Troca de transportadora', 'Entrega Programada',
       'Pedido cancelado pelo cliente',
       'Endereço do Cliente Destino não Localizado', 'Em rota de entrega',
       '1a Tentativa Cliente Ausente', 'Saiu para Entrega',
       'A caminho da loja', 'Em processo de devolução CD'], dtype=object)

In [15]:
mobile_relatorio = mobile_relatorio[mobile_relatorio['Tipo'] == 'Entrega Realizada Normalmente']

In [16]:
mobile_relatorio.Tipo.unique()

array(['Entrega Realizada Normalmente'], dtype=object)

In [17]:
quantidade_entregues = len(mobile_relatorio)

In [18]:
quantidade_entregues

3353

output_filename = os.path.join(caminho_dados, "Resultado_Monitoramento.xlsx")
print(f"Gerando o arquivo de resultado: {output_filename}", file=sys.stderr)

with pd.ExcelWriter(output_filename, engine='openpyxl') as writer:
    df_pendentes.to_excel(writer, sheet_name="Pendentes", index=False)
    df_finalizados.to_excel(writer, sheet_name="Finalizados", index=False)
    df_preventiva.to_excel(writer, sheet_name="Preventiva", index=False)

In [27]:
caminho = os.getcwd()

In [28]:
caminho

'c:\\Users\\pc\\Desktop\\Nova pasta\\Desktop\\Arquivos Domicilio\\preventiva-mobile\\testes'

In [ ]:
output_filename = os.path.join(caminho, "Resultado.xlsx")

In [5]:
preventiva.head(5)

   CD_Resp transportador (grupo)          Cidade Cliente  pedido_gemco
0     1100             DOMICILIO  SANTA BARBARA DE GOIAS    1101636148
1     1100             DOMICILIO                 GOIANIA    1096258498
2     1100             DOMICILIO                 GOIANIA    1103381975
3     1100             DOMICILIO                 GOIANIA    1103380688
4     1100             DOMICILIO    APARECIDA DE GOIANIA    1103278675

In [8]:
filtrado = preventiva.query(" `Cidade Cliente` != 'ITUMBIARA' ")

In [12]:
filtrado

     CD_Resp transportador (grupo)          Cidade Cliente  pedido_gemco
0       1100             DOMICILIO  SANTA BARBARA DE GOIAS    1101636148
1       1100             DOMICILIO                 GOIANIA    1096258498
2       1100             DOMICILIO                 GOIANIA    1103381975
3       1100             DOMICILIO                 GOIANIA    1103380688
4       1100             DOMICILIO    APARECIDA DE GOIANIA    1103278675
..       ...                   ...                     ...           ...
136     1100             DOMICILIO                ANAPOLIS    1103384339
137     1100             DOMICILIO                 GOIANIA    1103389496
138     1100             DOMICILIO                 GOIANIA    1103393818
139     1100             DOMICILIO                 GOIANIA    1103571413
140     1100             DOMICILIO                ANAPOLIS    1103521520

[139 rows x 4 columns]

In [3]:
preventiva_df = pd.read_excel('Relatorio_DOMICILIO_2025-10-31 (2).xlsx')

In [5]:
preventiva_df.columns

Index(['transportador (grupo)', 'Cidade Cliente', 'PEDIDO 1P/FULL'], dtype='object')

In [6]:
preventiva_df[['PEDIDO 1P/FULL']]

     PEDIDO 1P/FULL
0        1106390363
1        1106339530
2        1106463782
3        1106473559
4        1106378135
..              ...
128      1106444652
129      1106272027
130      1106276180
131      1106287686
132      1106115549

[133 rows x 1 columns]